# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink: /:title/
# relative_permalinks: true

# Setup
title:            Ryan Park
tagline:          'Be Better'
description:      'Try your best rather than be the best'
url:              https://ryanpark.dev
baseurl:          /

# Collections
collections:
  navigating-finances:
    output: true
    permalink: /navigating-finances/:title:output_ext

paginate:         5

# Custom vars
version:          2.1.0

plugins:
  - github-pages

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude: [Makefile, README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

include: [_redirects]
